# 1 ライブラリとデータの作成

In [1]:
import numpy as np
import torch
torch.manual_seed(1)

## 1.1 次元

In [2]:
x0 = torch.tensor(1)
print(x0.shape, x0)

torch.Size([]) tensor(1)


In [3]:
x1 = torch.tensor([1,2,3,4])
print(x1.shape, x1)

torch.Size([4]) tensor([1, 2, 3, 4])


In [4]:
x2 = torch.tensor([[1,2],[3,4]])
print(x2.shape, x2, sep="\n")

torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])


In [5]:
x3 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(x3.shape, x3, sep="\n")

torch.Size([2, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [6]:
x4 = torch.tensor([[[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]],[[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]]])
print(x4.shape, x4, sep="\n")

torch.Size([2, 3, 2, 2])
tensor([[[[1, 2],
          [3, 4]],

         [[1, 2],
          [3, 4]],

         [[1, 2],
          [3, 4]]],


        [[[1, 2],
          [3, 4]],

         [[1, 2],
          [3, 4]],

         [[1, 2],
          [3, 4]]]])


## 1.2 連続データ

In [7]:
x = torch.arange(5)
x

tensor([0, 1, 2, 3, 4])

In [8]:
x = torch.arange(1,5)
x

tensor([1, 2, 3, 4])

In [9]:
x = torch.arange(1,10,2)
x

tensor([1, 3, 5, 7, 9])

## 1.3 ランダムデータ

In [10]:
x = torch.rand(2,2)
x

tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])

In [11]:
x = torch.randn(3,3)
x

tensor([[ 0.0617,  0.6213, -0.4519],
        [-0.1661, -1.5228,  0.3817],
        [-1.0276, -0.5631, -0.8923]])

In [12]:
x = torch.normal(5, 1, size=(6,))
print(x.shape, x)

torch.Size([6]) tensor([4.9418, 4.8045, 4.0344, 5.4224, 5.2673, 4.5788])


# 2 データの変形

In [13]:
y = x.view(2,3)
print(y.shape, y, sep="\n")

torch.Size([2, 3])
tensor([[4.9418, 4.8045, 4.0344],
        [5.4224, 5.2673, 4.5788]])


In [14]:
y = x.unsqueeze(1)
print(y.shape, y, sep="\n")

torch.Size([6, 1])
tensor([[4.9418],
        [4.8045],
        [4.0344],
        [5.4224],
        [5.2673],
        [4.5788]])


# 3 データの参照

In [15]:
x = torch.randn(3,4)
x

tensor([[-0.5107, -1.5727, -0.1232,  3.5870],
        [-1.8313,  1.5987, -1.2770,  0.3255],
        [-0.4791,  1.3790,  2.5286,  0.4107]])

In [16]:
x[0,]

tensor([-0.5107, -1.5727, -0.1232,  3.5870])

In [17]:
x[:,2]

tensor([-0.1232, -1.2770,  2.5286])

In [18]:
x[:,0:2]

tensor([[-0.5107, -1.5727],
        [-1.8313,  1.5987],
        [-0.4791,  1.3790]])

# 4 numpyとtensor

In [19]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
y = torch.tensor(x)
y

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
y = torch.from_numpy(x)
y

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
y.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])